### ISSUE TITLE
check whether pelias index exists before importing records

### ISSUE THREAD

**Issue by sevko** [pelias/dbclient#11]
Importers will happily index data even when a Pelias elasticsearch index has _not_ been created. `dbclient` should check, if possible, whether the index exists before importing records.

**Comment by orangejulius** [comment]
This would be a really helpful feature to add. It's quite common to accidentally start an importer without rememebering to create the correct Elasticsearch schema by using the scripts in https://github.com/pelias/schema/.

Unfortunately, Elasticsearch tries to hard to be helpful, and will dutifully create a poorly set up schema that will not work for any Pelias queries. People who forgot to run the [create_index](https://github.com/pelias/schema/blob/master/scripts/create_index.js) script will only find out after they've imported their data that it was all for nothing, and they have to re-index.
