### ISSUE TITLE
Invalid bulk payload length

### ISSUE THREAD

**Issue by missinglink** [pelias/dbclient#2]
https://github.com/pelias/quattroshapes-pipeline/issues/12

**Comment by missinglink** [comment]
closing in favour of https://github.com/geopipes/elasticsearch-indexer/issues/1

**Comment by easherma** [comment]
Just putting this hear to save others from having to dig:

"The error invalid bulk payload length is emitted by pelias/dbclient when it's been asked to submit a bulk index request where the batch length is 0 (ie. the batch is empty)..."

https://github.com/pelias/quattroshapes/issues/12
