### ISSUE TITLE
Better stream management

### ISSUE THREAD

**Issue by orangejulius** [pelias/dbclient#76]
We have seen recently that dbclient really does a poor job of sending bulk requests to Elasticsearch at a slow enough rate to avoid overloading small clusters. In particular, if there is an error with one bulk request, we suspect it will retry that request, but it will do that _while new requests are being sent_.

This can cause a feedback loop where a single request timing out due to high load causes retries, that further increase the load on the cluster until the import fails.

One option to consider is using an existing elasticsearch bulk import tool like https://github.com/hmalphettes/elasticsearch-streams

Connects https://github.com/pelias/openaddresses/issues/328

**Comment by orangejulius** [comment]
It looks like based on default `elasticsearch-js` and Node.js settings, that this module will send out a potentially unlimited number of concurrent batch indexing requests to Elasticsearch. This would only happen if records are being processed by the importer using `dbclient` at a much faster rate than Elasticsearch can process them. However this is easily possible for a number of reasons:

* In a development environment, the resources allocated to Elasticsearch will often be very small.
* As an import progresses, Elasticsearch gets slower and slower at indexing new records, since the total number of records in Elasticsearch increases.
* Often times multiple importers are run in parallel, causing extra strain on Elasticsearch

We should be able to use the `createNodeAgent` function [configuration option](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html#config-options) in [elasticsearch-js](https://github.com/elastic/elasticsearch-js/) to control the maximum number of concurrent requests a bit.

**Comment by orangejulius** [comment]
This may also be related to https://github.com/elastic/elasticsearch-js/issues/196

**Comment by otbutz** [comment]
Did you tune the number of shards?

**Comment by orangejulius** [comment]
@otbutz In this case we were using 5 shards, the Elasticsearch default. I think on such a small machine shards likely make things worse, but it's a good stress test case.

**Comment by mapmeld** [comment]
Is there a way that I could set batch size to 1 when I am using the Docker installation?

**Comment by orangejulius** [comment]
@mapmeld currently it's only configurable by code in the importer. And to be clear, batch size 1 is _not_ the fix, because it has an extreme impact on import times.

However, you _can_ test out the actual proposed fix for the OpenAddresses importer, and doing so would be much appreciated :)

Change the `image` property in docker-compose.yml for the openaddresses importer to read like this:
` image: pelias/openaddresses:test-new-dbclient-2018-03-11-b6522df219022092c5f6de47135dfcc67f05bc15`

Let me know if it improves things.

**Comment by orangejulius** [comment]
Okay, I've tested the new `dbclient` branch with OA and OSM. It looks to completely resolve the rejected execution issue. Time to merge :)

**Comment by orangejulius** [comment]
For anyone else with this issue, an alternative solution put forth by @paraskashyap is to increase the bulk threadpool on Elasticsearch:

```
curl -XPUT localhost:9200/_cluster/settings -d '{ "transient" : { "threadpool.bulk.queue_size" : 500 } }'"
```

**Comment by mapmeld** [comment]
@orangejulius as a Docker newbie, what's the right place to make this change in the Dockerfile?

**Comment by orangejulius** [comment]
@mapmeld that last command can be run straight on the command line once you've started Elasticsearch. I don't think it's something that would go in a Dockerfile or docker-compose.yml

**Comment by orangejulius** [comment]
And also, to be clear. We expect this issue to be resolved with code changes, so that workaround shouldn't be needed in the long term.

**Comment by otbutz** [comment]
@orangejulius quoting an elastic [blog post](https://www.elastic.co/blog/why-am-i-seeing-bulk-rejections-in-my-elasticsearch-cluster) from Nov 2017:

> Increasing the size of the queue is not likely to improve the indexing performance or throughput of your cluster. Instead it would just make the cluster queue up more data in memory, which is likely to result in bulk requests taking longer to complete. The more bulk requests there are in the queue, the more precious heap space will be consumed. If the pressure on the heap gets too large, it can cause a lot of other performance problems and even cluster instability.
>
> Adjusting the queue sizes is therefore **strongly discouraged**, as it is like putting a temporary band-aid on the problem rather than actually fixing the underlying issue.

**Comment by orangejulius** [comment]
@otbutz Right, it's a good temporary workaround until our code changes to reduce the concurrency of our importers to something that is not overly excessive makes it to the production branches (it's going to be there soon).

Interestingly, they _did_ raise the default from 50 to 200 in Elasticsearch 5.

**Comment by orangejulius** [comment]
It's been nearly 6 months, and I haven't heard any complaints from folks running small builds regarding this issue. It's definitely still possible to overwhelm Elasticsearch if several importers are running in parallel and there are not a lot of resources dedicated to Elasticsearch, but this case isn't happening _all_ the time any more.

I'm going to close this, but if anyone else is still having issues, please let us know.
