### ISSUE TITLE
organize diagnostic/error messages and migrate to winston

### ISSUE THREAD

**Issue by sevko** [pelias/dbclient#8]
Migrate this package to the [winston](https://www.npmjs.com/package/winston) logger, and classify all the existing `console.log()` and `console.error()` messages into winston's `info`, `warn`, `error`, etc. categories, since they seem to currently be all over the place.

**Comment by missinglink** [comment]
LGTM. do we have a winston config file somewhere? ie. to specify which Transports it uses?

**Comment by sevko** [comment]
Not yet, but we're [discussing one](https://github.com/pelias/pelias/issues/28).

**Comment by sevko** [comment]
We're going to have to reconsider using `pelias-logger` if this module turns out to be generalized for anyone's use-case.
