### ISSUE TITLE
Update records

### ISSUE THREAD

**Issue by hkrishna** [pelias/dbclient#9]
I have a usecase for elasticsearch client doing updates (adding specific properties after an initial import). Does it make sense to extend dbclient to support updates http://www.elasticsearch.org/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-update or is it better to just use the exported esclient instead?

**Comment by missinglink** [comment]
This would be the first use of updates in the import process, can you please bring this up at our next video call?

**Comment by missinglink** [comment]
As discussed, the full range of bulk operations should be supported, including update and delete.

**Comment by missinglink** [comment]
This issue [has been resolved](https://github.com/geopipes/elasticsearch-indexer/blob/master/test/integration/transaction.js#L219) and so I'm closing this in favour of https://github.com/geopipes/elasticsearch-indexer/issues/1
